spring:
  datasource:
    url: jdbc:mysql://localhost:3301/sample_DB
    replicaUrl: jdbc:mysql://localhost:3302/sample_DB
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8081
